### ISSUE TITLE
New releases?

### ISSUE THREAD

**Issue by elpiel** [littlefs-project/littlefs-fuse#49]
Seems that the last tags are of 2.4.1 while `littlefs` was recently updated to 2.6.1

Would it be possible to tag all the releases, starting with the lates - 2.6.1?
It's good to have consistency but also include all versions so working and testing with specific littlefs version can be done.

**Comment by geky** [comment]
Ah, it looks like the CI here was missed when migrating to GitHub Actions. I didn't notice at all, thanks for pointing that out.

Fortunately littlefs-fuse is redundantly tested in littlefs's CI, so I think the only thing missing is the releases.

Will fix the CI and retroactively add tags for each littlefs bump. I think I may take the opportunity to desync littlefs-fuse's versions from littlefs though. littlefs-fuse doesn't expose littlefs's APIs, so API changes in littlefs don't need a minor bump in littlefs-fuse (but should still be at least a patch bump). This is necessary for littlefs-fuse to ever make an API change out-of-sync with the core littlefs repo.

**Comment by elpiel** [comment]
Awesome, great and thank you!

**Comment by elpiel** [comment]
@geky is it possible to build previous releases of littlefs-fuse at this point, now when the scripts have been fixed in #52 ?

**Comment by geky** [comment]
Ah sorry, it's not quite merged into master yet: https://github.com/littlefs-project/littlefs-fuse/pull/55

In littlefs I've been following a 2-step merge process for releases. It gives the CI a chance to test all PRs merged together and me a chance to write release notes. Though I realize it's probably a bit confusing since it's not GitHub's expected process.

**Comment by geky** [comment]
#55 is merged and the v2.7 release was created [here](https://github.com/littlefs-project/littlefs-fuse/releases).

I've also created git tags for all of the previous versions, though these were created manually so let me know if there were any mistakes:
https://github.com/littlefs-project/littlefs-fuse/tags

**Comment by elpiel** [comment]
current release of the LIttlefs2 crate has bindings to v2.2.1 but I don't see it released.
Maybe it's not a problem just saw it's missing.

I've experienced issues with the the draft PR that updates littlefs to newer version in this project but hopefully I'll be able to test the newer versions of littlefs

**Comment by geky** [comment]
Ah, I'm not really involved in the littlefs2 crate unfortunately, so you may have to raise that on their repo: https://github.com/trussed-dev/littlefs2.
