### ISSUE TITLE
Cannot compare commits between releases

### ISSUE THREAD

**Issue by ehmry** [littlefs-project/littlefs-fuse#75]
I'm the maintainer of the littlefs-fuse in nixpkgs and I don't like to update packages without a changelog, unless I can compare the commit history between releases.

Littlefs-fuse doesn't do either. People really do read look at those things and you don't have them then they come up with their own ungenerous conclusions.

**Comment by geky** [comment]
Hmm, is the problem the `git subtree merge --squash`? You can see the squashed commit history in the commit message, albeit in short form: https://github.com/littlefs-project/littlefs-fuse/commit/985bca0

littlefs-fuse is really just a small wrapper over littlefs, so in a sense the changeset really is just "bumped littlefs dependency".

I can add a link from littlefs-fuse's release notes to littlefs's release notes though, that seems like a good idea.

**Comment by geky** [comment]
I've added a link/note to the release notes:
https://github.com/littlefs-project/littlefs-fuse/releases/tag/v2.7.9
